properties:
# ------------------------------------------------
  data: 
    mssql:
      host: mssql.chinchalinchin.com
    logs:
      username: gmoore
      path: /var/log/
# ------------------------------------------------
  inventory:
    host:
      username: gmoore
      key: /Users/gmoore/.ssh/id_ed25519
    local:
      username: gmoore
      home: /Users/gmoore/
    k8s:
      host: https://localhost:6443
      username: gmoore
# ------------------------------------------------
  tools:
    artifactory:
      url: artifactory.chinchalinchin.com
    github:
      url: github.com/chinchalinchin
      groups: 
        ## LINUXMINT
        chinchalinchin: /home/grant/Projects/
        ## MACOS
        # chinchalinchin: /Users/gmoore/Home/Projects/
        # cumberland-cloud: /Users/gmoore/Home/tf-modules/
    jenkins:
      url: jenkins.chinchalinchin.com