task:
# ------------------------------------------------
  system: 
    guidelines: 
      coding: true
      latex: false
      pronouns: false
      notation: false
      interaction: false
    functions:
      linguistic: false
    procedures:
      poetics: false
# ------------------------------------------------
  ticket: 
    title: "<TITLE>"
    content: |
      <task>
    shell: [ ]
      # - <cmd>
# ------------------------------------------------
  data:
    logs: []
      # - parameters:
      #     host: <hostname>
      #     app: <apache | java-app>
      #     search:
      #       # --- APACHE LOG FORMAT
      #       # format: '<DD/Month/YYYY:HH:MM:SS>''
      #       # --- JAVA LOG FORMAT
      #       # format: '<YYYY-MM-DD HH:MM:SS>''
      #       # ------------------------
      #       # start: 14/Feb/2026:13:36:00
      #       # end: 14/Feb/2026:13:37:00
      #       start: '2026-02-15 11:20:00'
      #       end: '2026-02-15 11:21:00'
      #   views:
      #     search: false
    mssql: []
      # - parameters:
      #     database: <database_name>
      #     query: <query>
      #   views:
      #     query: true
# ------------------------------------------------
  inventory:
    # -------------------------------------------
    host: []
      # - parameters:
      #     hostname: integ.chinchalinchin.com
      #     command: 
      #       - sudo docker ps
      #   views:
      #     certificates: false
      #     command: true
      #     docker: false
      #     specifications: false

    # -------------------------------------------
    k8s: []
      # - parameters:
      #     namespace: devops
      #   views:
      #     pods: true
# ------------------------------------------------
  tools:
    # -------------------------------------------
    artifactory: []
      # - parameters:
      #     repo: chinchalinchin
      #     artifact: java-app
      #   views:
      #     latest: true
    # -------------------------------------------
    github: []
    #   - parameters:
    #       repo: golem
    #       group: chinchalinchin
    #     views:
    #       directory: true
    #       ai_doom_docs: true
    #       ai_doom_src: true
    # -------------------------------------------
    prometheus: []
      # - parameters:
      #     hostname: testing.chinchalinchin.com
      #     application: java-app
      #   views: 
      #     metrics: true
    # -------------------------------------------
    jenkins: []
      # - parameters:
      #     job: dxs-tasks
      #   views:
      #     config: false
      #     console: false
    # -------------------------------------------