# -----------------------------------------------------------------------------------
# ----------------------------- VIEW CONFIGURATION ----------------------------------
# -----------------------------------------------------------------------------------
# TODO: MACOS Spec Command: system_profiler SPHardwareDataType
views:
  # ----------------------------- INVENTORY VIEWS
  inventory:
    # --- 1. HOST VIEWS
    host:
      certificates:
        # Command to present certificate context.
        cmd: ls -al /etc/gerberlife/SSL
      docker:
        # Commands to present Docker context.
        containers: sudo docker ps
        images: sudo docker images
        stats: sudo docker stats --no-stream
      specifications:
        # Commands to present host context.
        os: lsb_release -a
        cpu: lscpu
        memory: free
        processes: top -b -n 1 | head -n 17
    # --- 2. K8S VIEWS
      k8s:
        pods: {}
  # ----------------------------- DATA VIEWS
  data: 
    mssql:
      specifications:
        version: SELECT @@VERSION;
  # ----------------------------- TOOLS VIEWS
  tools:
    # --- 1. ARTIFACTORY VIEWS
    artifactory:
      latest: {}
    # --- 2. DOCKERHUB VIEWS
    dockerhub: {}
    # --- 3. GITHUB VIEWS
    github:
      blobs:
        # ------------------ ELARA
        # ----------------------------
        elara_build:
          title: "Elara: Build Files"
          files:
            requirements.txt: text
            Dockerfile: docker
            source/conf.py: python
        elara_linguistics:
          title: "Elara: Linguistic Scripts"
          files:
            source/.scripts/py/linguistics/poetics.py: python
            source/.scripts/py/linguistics/rhyme.py: python
            source/.scripts/py/linguistics/syllabify.py: python
            source/.scripts/py/linguistics/synonyms.py: python
        elara_extensions:
          title: "Elara: Extensions"
          files:
            source/.extensions/directives/panels.py: python
            source/.extensions/roles/classes.py: python
            source/.extensions/roles/widgets.py: python
            source/.templates/panels/map.html.j2: jinja2
            source/.templates/panels/rss.html.j2: jinja2
            source/.templates/panels/verse.html.j2: jinja2
            source/.templates/widgets/back.html.j2: jinja2
            source/.templates/widgets/share.html.j2: jinja2
        elara_static:
          title: "Elara: Static Files"
          files:
            source/.static/css/custom.css: css
            source/.static/rst/links.rst: rst
        # ------------------ TERRAFORM
        # ----------------------------
        tf_platform:
          title: 'Terraform Module: Core'
          files:
            README.md: markdown
            data.tf: terraform
            locals.tf: terraform
            outputs.tf: terraform
            variables.tf: terraform
            metadata/clients.json: json
            metadata/environments.json: json
            metadata/regions.json: json
            metadata/subnets.json: json
        tf_ec2: 
          title: 'Terraform Module: S3'
          files:
            README.md: markdown
            data.tf: terraform
            locals.tf: terraform
            modules.tf: terraform
            outputs.tf: terraform
            resources.tf: terraform
            terraform.tf: terraform
            variables.tf: terraform
            user-data/user-data.sh: bash
        tf_iam:
          title: 'Terraform Module: IAM'
          files: 
            README.md: markdown
            data.tf: terraform
            locals_policies.tf: terraform
            locals_roles.tf: terraform
            locals.tf: terraform
            modules.tf: terraform
            outputs.tf: terraform
            resources_policies.tf: terraform
            resources_roles.tf: terraform
            terraform.tf: terraform
            variables.tf: terraform
            policies/platform/tagging.tftpl: template
            policies/platform/logging.tftpl: template
            policies/sts/assume-role.tftpl: template
        # ---------------------- GOLEM
        # ----------------------------
        # -------------- DOCUMENTATION
        golem_board:
          title: Golem Task Board
          files:
            docs/board/roadmap.md: markdown
            docs/board/issues.md: markdown
        golem_docs:
          title: "Golem Documentation"
          files:
            README.md: markdown
            # docs/index.md: markdown
            docs/configuration.md: markdown
            docs/guide.md: markdown
        golem_theory:
          title: "Golem Documentation (Theory)"
          files:
            docs/environment.md: markdown
            docs/model/philosophy.md: markdown
            docs/model/brain.md: markdown
            docs/model/training.md: markdown
        # -------------- SOURCE CODE
        # ----- CONFIGURATION & ENTRYPOINTS
        golem_core: 
          title: "Golem Core"
          files: 
            main.py: python
            app/utils/doom.py: python
        golem_config:
          title: "Golem Configuration"
          files: 
            requirements.txt: text
            conf/app.yaml: yaml
            conf/simple.cfg: conf
        # ----- MODULES
        golem_metrics:
          title: "Golem Metrics Source Code"
          files:
            app/metrics/audit.py: python
            app/metrics/examine.py: python
            app/metrics/inspect.py: python
            app/metrics/summary.py: python
        golem_pipeline:
          title: "Golem Pipeline Source Code"
          files:
            app/pipeline/intervene.py: python
            app/pipeline/record.py: python
            app/pipeline/run.py: python
            app/pipeline/train.py: python
        golem_model:
          title: "Golem Model Source Code"
          files: 
            app/models/config.py: python
            app/models/brain.py: python
            app/models/dataset.py: python
            app/models/loss.py: python
            app/utils/model.py: python
        golem_client:
          title: "Golem Client Source Code"
          files:
            docker-compose.yml: yaml
            Dockerfile.agent: dockerfile
            app/client/agent.py: python
            app/client/arena.py: python
            app/client/host.py: python
        golem_sample:
          title: "Golem Random Source Code"
          files:
            Dockerfile.oblige: dockerfile
            app/sample/init.py: python
            app/sample/interfaces.py: python
            app/sample/generate.py: python
            app/sample/randomize.py: python
        # -------------- CONTINUOUS INTEGRATION
        golem_ci:
          title: "Golem Continuous Integration"
          files:
            .github/workflows/ci.yml: yaml
            Dockerfile.agent: dockerfile
            Dockerfile.ci: dockerfile
            tests/test_dataset.py: python
        golem_mkdocs:
          title: "Golem MkDocs Configuration"
          files:
            .github/workflows/ci.yml: yaml
            Dockerfile.ci: dockerfile
            mkdocs.yml: yaml
            docs/javascripts/mathjax.js: javascript
        # -------------- EVERYTHING ELSE
        golem_etc:
          title: "Golem ETC"
          files:
            app/client/__init__.py: python
            app/metrics/__init__.py: python
            app/models/__init__.py: python
            app/pipeline/__init__.py: python
            app/utils/conf.py: python
            app/templates/audit.j2: jinja2
            app/templates/inspect.j2: jinja2
            conf/basic.cfg: conf
            conf/classic.cfg: conf
            conf/fluid.cfg: conf
            docs/board/closed/issues.md: markdown
            docs/board/closed/phases.md: markdown
    # --- 4. JENKINS VIEWS
    jenkins:
      config: {}
      console: {}