version: 0.2

env:
  secrets-manager:
    PYPI_USERNAME: "cumberland-cloud/pypi:username"
    PYPI_PASSWORD: "cumberland-cloud/pypi:token"

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - pip install --upgrade pip
      - pip install twine build 

  build:
    commands:
      - python -m build

  post_build:
    commands:
      - twine upload dist/* \
        --repository-url https://upload.pypi.org/legacy/ \
        --username $PYPI_USERNAME \
        --password $PYPI_TOKEN

artifacts:
  files:
    - dist/* 