task:
# ------------------------------------------------
  system: 
    guidelines: 
      coding: true
      latex: false
      pronouns: false
      notation: false
      interaction: false
    functions:
      linguistic: false
    procedures:
      poetics: false
# ------------------------------------------------
  ticket: 
    # -------------------------------------------
    title: "Golemn: Documentation Update: {{ target_doc }}"
    # -------------------------------------------
    content: |
      Update the indicated documentation page. Be as thorough and precise as possible. The target audience is technical and versed in the subject matter. 

      Do not remove information. You may edit or add information to bring the documentation up to date with the current state of code, but do not reduce the amount of content, unless that content has been deprecated.
    # -------------------------------------------
    shell: []
# ------------------------------------------------
  tools:
    # -------------------------------------------
    github: 
      - parameters:
          repo: golem
          group: chinchalinchin
        views:
          directory: false
          # Golem Documentation Views
          golem/board: false
          golem/docs: true
          golem/theory: true
          golem/mkdocs: true
          # Golem Source Code Views
          golem/config: false
          golem/pipeline: false
          golem/model: false
          golem/client: false
          golem/etc: false
          # Golem Testing Views
          golem/ci: false