task:
# ------------------------------------------------
  system: 
    guidelines: 
      coding: true
      latex: false
      pronouns: false
      notation: false
      interaction: false
    functions:
      linguistic: false
    procedures:
      poetics: false
# ------------------------------------------------
  ticket: 
    title: "<title>"
    content: |
      <task>
    shell: [ ]
      # - <cmd>
# ------------------------------------------------
  data:
    logs: []
      # - parameters:
      #     host: <host>
      #     app: <apache | java>
      #     search:
      #       # --- APACHE LOG FORMAT
      #       #   <DD/Mon/YYYY:HH:MM:SS>
      #       start: 'DD/Mon/YYYY:HH:MM:SS'
      #       end: 'DD/Mon/YYYY:HH:MM:SS
      #       # --- JAVA LOG FORMAT
      #       #   <YYYY-MM-DD HH:MM:SS>'
      #       start: 'YYYY-MM-DD HH:MM:SS'
      #       end: 'YYYY-MM-DD HH:MM:SS'
      #   views:
      #     search: false
    mssql: []
      # - parameters:
      #     database: <database>
      #     query: <query>
      #   views:
      #     query: true
      #     specifications: true
# ------------------------------------------------
  inventory:
    # -------------------------------------------
    host: []
      # - parameters:
      #     hostname: <hostname>
      #     command: 
      #       - <command>
      #   views:
      #     certificates: false
      #     command: false
      #     docker: false
      #     specifications: false

    # -------------------------------------------
    k8s: []
      # - parameters:
      #     namespace: <namespace>
      #   views:
      #     pods: false
# ------------------------------------------------
  tools:
    # -------------------------------------------
    artifactory: []
      # - parameters:
      #     repo: <repo>
      #     artifact: <artifact>
      #   views:
      #     latest: false
    # -------------------------------------------
    github: []
    #   - parameters:
    #       repo: <repo>
    #       group: <group>
    #       board: 
    #         phase: <phase>
    #         action: <action>
    #     views:
    # # ------------------------ GENERAL VIEWS
    #       actions: false
    #       directory: false
    #       docs: false
    #       board: false
    #       python: false
    # # ------------------------ CUSTOM VIEWS
    #       app/main: false
    # # ...
    # -------------------------------------------
    prometheus: []
      # - parameters:
      #     hostname: <hostname>
      #     application: <application>
      #   views: 
      #     metrics: false
    # -------------------------------------------
    jenkins: []
      # - parameters:
      #     job: <job>
      #   views:
      #     config: false
      #     console: false
    # -------------------------------------------