name: Deploy to S3 and CloudFront

on:
  push:
    branches:
      - master
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    container:
      image: chinchalinchin/elara-builder:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Make upload script executable
        run: chmod +x upload.sh

      - name: Build and Deploy
        env:
          ELARA_BUCKET: ${{ secrets.ELARA_BUCKET }}
          ELARA_DIST: ${{ secrets.ELARA_DIST }}
        run: ./upload.sh --build --invalidate