task:
# ------------------------------------------------
  context: true
# ------------------------------------------------
  # system: 
  #   guidelines: 
  #     coding: true
# ------------------------------------------------
  ticket: 
    # -------------------------------------------
    title: "Ontology: Design & Architecture"
    # -------------------------------------------
    content: |
      Discuss the design and architecture of this application. Evaluate and critique it. Suggest improvements. 
      
      Keep in mind, this is a 2D game engine that is cropping pre-rendered assets on the fly, not rendering fully-textured raytraced 3D graphics from scratch. 
    # -------------------------------------------
    shell: []
# ------------------------------------------------
  tools:
    # -------------------------------------------
    github: 
      - parameters:
          repo: ontology
          group: chinchalinchin
        views:
          directory: true
          ontology/docs: false
          ontology/board: false
          ontology/app/assets: true
          ontology/app/game: true
          ontology/app/main: true
          ontology/app/models: true
          ontology/app/input: true
          ontology/cython: true