task:
# ------------------------------------------------
  context: true
# ------------------------------------------------
  # system: 
  #   guidelines: 
  #     coding: true
# ------------------------------------------------
  ticket: 
    # -------------------------------------------
    title: "Ontology: Design & Architecture"
    # -------------------------------------------
    content: |
      Discuss the design and architecture of this application with respect to the current phase of the Task Board. Evaluate and critique it. Suggest improvements, if applicable. Discuss what needs modified in the task backlog, if changes are required.
      
      Keep in mind, this is a 2D game engine that is cropping pre-rendered assets on the fly, not rendering fully-textured ray-traced 3D graphics from scratch. 

      I believe the load() in libs/render.pyx should probably be in the libs/registry.pyx, along with the definition of the TexturePtr wrapper. Anaylze the design of the Registry. Ensure tasking aligns with architecture.
    # -------------------------------------------
    shell: []
# ------------------------------------------------
  tools:
    # -------------------------------------------
    github: 
      - parameters:
          repo: ontology
          group: chinchalinchin
        views:
          directory: true
          ontology/docs: true
          ontology/board: true
          ontology/app/assets: true
          ontology/app/game: true
          ontology/app/main: true
          ontology/app/models: true
          ontology/app/input: true
          ontology/cython: true