task:
# ------------------------------------------------
  context: true
# ------------------------------------------------
  # system: 
  #   guidelines: 
  #     coding: true
# ------------------------------------------------
  ticket: 
    # -------------------------------------------
    title: "Ontology: Cython"
    # -------------------------------------------
    content: |
      Evaluate the Cython setup. Document how to compile the libraries and import them in the README below. Add instructions for getting VSCode to recognize the libraries.

      # Ontology

      ## Development Setup

      Install and build the application dependencies,

      ```bash
      # 1. Install Dependencies
      ## MacOS
      brew install sdl2 sdl2_image
      ## Linux
      sudo apt install libsdl2-dev libsdl2-image-dev

      # 2. Build Cython Libraries
      python setup.py build_ext --inplace
      ```

      ## Index

      This section provides an overview of the project's directory and file structure.

      - `setup.py`: Script for compiling Cython libraries.
      - `main.py`: Application entrypoint.

      ### /docs

      `mkdocs` documentation markdown files.

      ### /libs

      - `render.pyx`: Cython interfaces for SDL2 rendering
      - `registry.pyx`: Cython class for storing textures 
      - `core.pyx`: Cython data classes.
      - `math.pyh`: Cython calculations

      ### /src

      - `cli.py`: Application command line interface.
      - `/src/app/`: Application source code.
      - `/src/assets/`: Application assets.
      - `/src/data/`: Application data.


      ## References

      - [Cython](https://pypi.org/project/Cython/)
      - [SDL2](https://wiki.libsdl.org/SDL2/FrontPage)
      - [LiberatedPixelCup](https://lpc.opengameart.org/static/LPC-Style-Guide/build/styleguide.html)
    # -------------------------------------------
    shell: []
# ------------------------------------------------
  tools:
    # -------------------------------------------
    github: 
      - parameters:
          repo: ontology
          group: chinchalinchin
          phase: i
        views:
          directory: true
          board: false
          docs: true
          python: true
          ontology/app/main: true
          ontology/app/input: false
          ontology/app/models: false
          ontology/app/game: false
          ontology/app/assets: false
          ontology/cython/core: true
          ontology/cython/graphics: true
          ontology/schemas/assets: false
          ontology/schemas/intents: false
          ontology/schemas/items: false