task:
# ------------------------------------------------
  context: true
# ------------------------------------------------
  # system: 
  #   guidelines: 
  #     coding: true
# ------------------------------------------------
  ticket: 
    # -------------------------------------------
    title: "Ontology: Debugging"
    # -------------------------------------------
    content: |
      Assist in debugging the app invocation in the [next section](#shell-localhost).
    # -------------------------------------------
    shell: 
      - ls /home/grant/Projects/ontology/src/data/state/world-01
      - cat /home/grant/Projects/ontology/src/data/state/world-01/tiles.yaml
      - cat /home/grant/Projects/ontology/src/assets/main.yaml
      - cat /home/grant/Projects/ontology/src/assets/tiles/main.yaml
      - python /home/grant/Projects/ontology/src/cli.py construct world-01 --layer 0 --out /home/grant/Projects/ontology

# ------------------------------------------------
  tools:
    # -------------------------------------------
    github: 
      - parameters:
          repo: ontology
          group: chinchalinchin
          board: 
            phase: i
            action: phase
        views:
          directory: true
          board: false
          docs: true
          python: true
          ontology/app/main: false
          ontology/app/input: true
          ontology/app/config: true
          ontology/app/models: true
          ontology/app/hooks: true
          ontology/app/game: true
          ontology/app/assets: true
          ontology/cython/core: false
          ontology/cython/graphics: false
          ontology/schemas/assets: false
          ontology/schemas/intents: false
          ontology/schemas/items: false
          ontology/schemas/player: false