task:
# ------------------------------------------------
  context: true
# ------------------------------------------------
  # system: 
  #   guidelines: 
  #     coding: true
# ------------------------------------------------
  ticket: 
    # -------------------------------------------
    title: "Ontology: Documentation"
    # -------------------------------------------
    content: |
      Update the following mkdocs pages to reflect the current state of the application:
      
      - <docs>
    # -------------------------------------------
    shell: []
# ------------------------------------------------
  tools:
    # -------------------------------------------
    github: 
      - parameters:
          repo: ontology
          group: chinchalinchin
        views:
          directory: true
          board: true
          docs: true 
          ontology/app/main: true
          ontology/app/input: true 
          ontology/app/models: true
          ontology/app/game: true
          ontology/app/assets: true
          ontology/cython: true
          ontology/schemas: true