task:
# ------------------------------------------------
  context: true
# ------------------------------------------------
  system: null
# ------------------------------------------------
  ticket: 
    # -------------------------------------------
    title: "Ontology: Groom"
    # -------------------------------------------
    content: |
      Discuss the design and architecture of this application with respect to the current phase of the Task Board. Do not implement anything; instead step back and examine the big picture. Focus on the logical flow of the application. Suggest improvements, if applicable. Discuss what needs modified in the task backlog, if changes are required. Ensure tasking aligns with architecture. Break everything down, step-by-step.
      
      **Grooming Guidelines**

      - Create tasks in the Task Board to achieve the next Phase of the application. Lay out, step-by-step, what must be done.
      - Keep in mind, this is a 2D game engine that is cropping pre-rendered assets on the fly, not rendering fully-textured ray-traced 3D graphics from scratch. 
      - Do not suggest C-level optimizations at this stage of the application.
      - Do not worry about Python GIL locks yet, unless concerns are severe.

    # -------------------------------------------
    shell: []
# ------------------------------------------------
  tools:
    # -------------------------------------------
    github: 
      - parameters:
          repo: ontology
          group: chinchalinchin
          board: 
            phase: iii
            action: implement
        views:
          directory: true
          board: true
          docs: true
          python: false
          ontology/app/main: false
          ontology/app/config: false
          ontology/app/models: true
          ontology/app/hooks: true
          ontology/app/game: true
          ontology/app/assets: true
          ontology/libs/core: false
          ontology/libs/graphics: false
          ontology/schemas/assets: false
          ontology/schemas/intents: false
          ontology/schemas/items: false
          ontology/schemas/player: false
          ontology/schemas/widgets: true