task:
# ------------------------------------------------
  context: true
# ------------------------------------------------
  system: 
    guidelines: 
      coding: true
# ------------------------------------------------
  ticket: 
    # -------------------------------------------
    title: "Ontology - Implement"
    # -------------------------------------------
    content: |
      **Priorities**

      - Implement the next task on the Task Board. See [Task Board](#view-ontology-task-board) for current tasking.
    # -------------------------------------------
    shell: []

# ------------------------------------------------
  tools:
    # -------------------------------------------
    github: 
      - parameters:
          repo: ontology
          group: chinchalinchin
          board: 
            phase: '04-03'
            action: refactor
        views:
          directory: true
          board: true
          docs: true
          python: false
          ontology/main: false
          ontology/app/assets: true
          ontology/app/config: false
          ontology/app/game: true
          ontology/app/game/logic/maps: false
          ontology/app/game/logic/mechanics: true
          ontology/app/game/logic/mechanics/motion: true
          ontology/app/game/logic/mechanics/spatial: true
          ontology/app/game/logic/mechanics/intentional: false
          ontology/app/hooks: false
          ontology/app/models: true
          ontology/data/configuration: false
          ontology/data/state: false
          ontology/data/properties: false
          ontology/libs/core: true
          ontology/libs/graphics: false
          ontology/schemas/assets: false
          ontology/schemas/configurations: false