task:
# ------------------------------------------------
  context: true
# ------------------------------------------------
  system: 
    guidelines: 
      coding: true
# ------------------------------------------------
  ticket: 
    # -------------------------------------------
    title: "Ontology - Implement"
    # -------------------------------------------
    content: |
      Implement the next task on the Task Board.
    # -------------------------------------------
    shell: []
# ------------------------------------------------
  tools:
    # -------------------------------------------
    github: 
      - parameters:
          repo: ontology
          group: chinchalinchin
          board: 
            phase: ii-i
            action: refactor
        views:
          directory: true
          board: true
          docs: true
          python: false
          ontology/main: false
          ontology/app/assets: true
          ontology/app/config: true
          ontology/app/game: true
          ontology/app/hooks: true
          ontology/app/models: true
          ontology/libs/core: false
          ontology/libs/graphics: true
          ontology/schemas/assets: true
          ontology/schemas/intentions: false
          ontology/schemas/mappings: false
          ontology/schemas/menus: false