task:
# ------------------------------------------------
  context: true
# ------------------------------------------------
  system: 
    guidelines: 
      coding: true
# ------------------------------------------------
  ticket: 
    # -------------------------------------------
    title: "Ontology: Design & Architecture"
    # -------------------------------------------
    content: |
      Read over the documentation and the current source code. Update the project plan detailed in the Board. Create tasks and subtasks that will results in the completion of a project that meets the specifications detailed in the documentation.
    # -------------------------------------------
    shell: []
# ------------------------------------------------
  tools:
    # -------------------------------------------
    github: 
      - parameters:
          repo: ontology
          group: chinchalinchin
        views:
          directory: true
          ontology/docs: true
          ontology/app: true
          ontology/board: true
          ontology/app/interface: true
          ontology/app/models: true
          ontology/app/world: true
          ontology/cython: true