task:
# ------------------------------------------------
  context: true
# ------------------------------------------------
  system: null
# ------------------------------------------------
  ticket: 
    # -------------------------------------------
    title: "Ontology: Root Cause Analysis"
    # -------------------------------------------
    content: |
      Assist in debugging the incident and create an RCA. Suggest ways of approaching the problem. Provide concrete debugging steps. If information is not present, do not make inferences; implement ways of scraping and dumping the data. The goal is to perform an exhaustive forensic autopsy of the application and its environment to isolate the cause of the behavior. Do not alter code unless it is to inject debugging output.
    # -------------------------------------------
    shell: []
# ------------------------------------------------
  tools:
    # -------------------------------------------
    github: 
      - parameters:
          repo: ontology
          group: chinchalinchin
          board: 
            phase: 2026-08-09
            action: report
        views:
          # ------------------------------
          # ----------------- GITHUB VIEWS
          actions: true
          directory: true
          board: true
          docs: true
          python: false
          # ------------------------------
          # ------------------ SOURCE CODE
          ontology/main: false
          # ---- APPLICATION LIBRARIES
          ontology/app/assets: true
          ontology/app/config: false
          ontology/app/game: false
          ontology/app/game/logic/maps: false
          ontology/app/game/logic/mechanics: false
          ontology/app/game/logic/mechanics/motion: false
          ontology/app/game/logic/mechanics/spatial: false
          ontology/app/game/logic/mechanics/intentional: false
          ontology/app/hooks: true
          ontology/app/models: true
          # ---- CYTHON LIBRARIES
          ontology/libs/core: false
          ontology/libs/graphics: true
          # ---- DATA & CONFIGURATION
          ontology/data/properties: true
          ontology/data/configuration: false
          ontology/data/state: false
          # ----- UNIT TESTS
          ontology/tests/unit: true
          ontology/tests/unit/app: false
          ontology/tests/unit/libs: true