task:
# ------------------------------------------------
  context: true
# ------------------------------------------------
  # system: 
  #   guidelines: 
  #     coding: true
# ------------------------------------------------
  ticket: 
    # -------------------------------------------
    title: "Ontology: Data Structures"
    # -------------------------------------------
    content: |
      Discuss the design and schemas of the data structures (state, properties, recipes, etc.) with respect to the current phase of the Task Board and the overall goal of the project. Evaluate and critique it. 

      What models need further consideration, development and attention? What potential bugs or code issues arise from the data structures in the game? 
      
      Suggest improvements, if applicable. Discuss what needs modified in the task backlog, if changes are required to any of the models. Ensure tasking aligns with architecture.
      
      Keep in mind, this is a 2D game engine that is cropping pre-rendered assets on the fly, not rendering fully-textured ray-traced 3D graphics from scratch. 
    # -------------------------------------------
    shell: []
# ------------------------------------------------
  tools:
    # -------------------------------------------
    github: 
      - parameters:
          repo: ontology
          group: chinchalinchin
          phase: i
        views:
          directory: true
          board: true
          docs: true
          ontology/app/main: true
          ontology/app/input: true
          ontology/app/models: true
          ontology/app/game: true
          ontology/app/assets: true
          ontology/cython/core: true
          ontology/cython/graphics: true
          ontology/schemas: true